### ISSUE TITLE
Release contains huge amount of unneeded sources

### ISSUE THREAD

**Issue by thheller** [eihli/clj-tightly-packed-trie#1]
The `[com.owoga/tightly-packed-trie "0.2.3"]` release on clojars is 19mb big and contains many sources it should not contain. This includes the `org.clojure/clojure`, `org.clojure/clojurescript` files and many many more. Looks like this might be accidentally published as a uberjar? You should only package release your own sources as part of a library?

If used as a library this will manifest as users ending up using a different version (the version bundled in the .jar) over one they may have specified in their own `deps.edn` or `project.clj`.

**Comment by eihli** [comment]
Thanks for letting me know! `0.3.0` is 126K.
