### ISSUE TITLE
Project License?

### ISSUE THREAD

**Issue by respatialized** [eihli/clj-tightly-packed-trie#2]
Hi there - I noticed that this project doesn't have a published license. I was interested in implementing the Knuth-Liang hyphenation algorithm, but am uncertain about the implications of using this library to do so. Clarifying the project's license would be helpful for myself and for other potential users!

**Comment by eihli** [comment]
Thanks for the heads up. How's the GPLv3 license sound? https://github.com/eihli/clj-tightly-packed-trie/blob/main/LICENSE
